### ISSUE TITLE
Allow more control over table creation

### ISSUE THREAD

**Issue by pekasen** [Leibniz-HBI/ponyexpress#26]
Right now only table names are configured and table structure itself is determined by incoming data. Where as both `node_list` and `edge_list_dense` are under the control of the connector and contain whatever the connector spouts out. `edge_list_sparse`is hard wired to be an aggregate over `source`and `target` with `weight`as count of the sparse edge table.

It would be however conceivable for a user to determine which columns should be included in the database (and which not) and how/whether an aggregation of the sparse table is necessary and how it should be implemented. E.g.:

```yaml
node_table:
  name: node_list
  columns:
    - view_count
    - subscriber_count
   metrics:  # metrics to be calculated before each pass of the sampler
     - degrees
     - kcoreness
edge_table:
  sparse:
    name: edges_sparse
    mode: weighted_simple  # to indicate we should aggregate the dense edges before passing them into the sampler
    aggregations:   # allow metrics which can passed into `pd.DataFrame().agg()`.
    - message_view_count: sum
    - message_forward_count: sum
  dense:
  name: edges_dense
    columns:  # columns to keep
    - message_view_count
    - message_forward_count
```
