### ISSUE TITLE
feat: add routing middleware for multi-layer sampling

### ISSUE THREAD

**Issue by pekasen** [Leibniz-HBI/ponyexpress#36]
**NOW**:

The `connector` is responsible for parsing incoming data into edges; what and how to parse is hard-coded in each connector.

**PROBLEM**:

That makes it difficult to adapt to different scenarios and parsing multi-platform data impossible, as each connector would need to know which connector to dispatch next.

**SOLUTION**:

A middleware that consumes the *raw* data coming from the connector and processes it.

E.g. consider the following routing specification as a snippet of the ponyexpress configuration, where we address how edges are generated from the incomgin data:

```yaml
...
routing:
  telegram:
    from: handle
    to:
      - field: url
        pattern: ^t.me/$(\w+)$
        type: telegram
        edge_type: link
      - field: forwarded_from
        type: telegram
        edge_type: forward
      - field: text
        pattern: @$(\w+)
        type: telegram
        edge_type: mention
      - field: url
        pattern: ^twitter.com/(\w+)$
        type: twitter/timeline
        edge_type: to_twitter
```

For each object in `routing` we specify how incoming data from the connector should be parsed. E.g. we specify multiple values for the `url`-field, one for links that link back into telegram and one for links into Twitter. Which part of the URL or other field's content should be used as a node-identifier for that edge is given by RegEx with a single capture group. Further we specify which connector should be dispatched if we need to follow that edge during the sampling process. The values of `edge_type` are stored in each edge to discern multi-layer networks by utilizing property graphs.

Consider matching the above spec with the following data:

| handle | url                   | text                                          |
|----------|---------------------|----------------------------------------|
| user1  | https://t.me/s/user2 | Hello, @user3                |
| user2 | https://twitter.com | ------- |
 
Edges generated by this would be:

| from             | to                     | edge_type                  |
|------------------|--------------------|------------------------------|
| telegram-user1            | telegram-user2              | link |
| telegram-user1           | telegram-user3 | mention |
| telegram-user2           | twitter-user | to_twitter |
