### ISSUE TITLE
implement spikyball sampling

### ISSUE THREAD

**Issue by pekasen** [Leibniz-HBI/ponyexpress#4]
ATM there is only a stub implementation for the Spiky-Ball-sampler. Although the algorithm is quite easy to implement, it is crucial too assert some interface choices before further implementation: Foremost, the sampling function needs to know another function to calculate probalities per edge to be sampled. This function cannot be fixed as coefficients need to be adjustable and columns from the edge and node tables need to be taken into the calculation, e.g. sampling a social network ranked by follower-/subscription-count. Thus, we need a notation method in order to specify which columns to weight in which way.

This notation could take the shape of a key-value-pair of column-name and a weight, e.g. a configuration snippet could look like this:

```yaml
strategy:
  spikyball:
    layer_max_size: 150  
    sampler:
      source_node_probability:
        coefficient: 1.4
        weights:
           indegree: 1
      target_node_probality:
        coefficient: 1.7
        weights:
           outdegree: 1
      edge_probability:
        coefficient: .5
        weights:
           weight: .5
```
